# ICASSP Submission Roadmap

## Abstract

## Intro

## Notation and Background

* evolutionary spectra
* UMPs

### Time-frequency Spectra and the Multitaper Method

* multitaper
* HRS
* SWHRS

### Improving Multitaper Spectrograms via NSQI Theory

* NSQI [summarize + ref dAVE 2005]
* MTFSE
* BCMTFSE

## NSQI-based Spectrogram Modifications using Second-Order Taylor Approximations

* CBC [rename to second-order BCS? Or BCS-2? Where S stands for Spectrogram]

## Manipulation of UMP Spectrograms

### Estmating the Modulating Function and Stationary Series of a UMP

* getting g(t)
* eigenvalue problem
* getting y(t)

### Estmating the Spectrum of a UMP's Underlying Stationary Series

* getting smoothed y(f)
* discuss implications for stationary series as well

### Techniques for Spectrogram smoothing

* outer product of g(t), y(f)
* propose iteration?

## Results by way of Simulation

### CBC

### g(t) and y(t)

### Smoothed Spectrograms

### Smoothed Spectra and the Stationary Case

## Discussion

* Potential applications [BSS]
* Formal evaluation of performance (everything's visual so far)
    - Bias/Variance Properties, etc.

## Conclusion

## Refrences
* Priestly
* dAVE (old multitaper stuff)
* dAVE 2005 [NSQI]
* Azadeh [Thesis, SSP]
* Percy and Waldy latest book (2020)











