## Prelims

```{r packages}
## --- Packages 
library(multitaper)   # spec.mtm, etc.
library(pbapply)      # Progress bar for apply() functions
library(kableExtra)   # Nice Tables
library(itsmr)        # Time series stuff, used here for ARMA
library(animation)    # For creating gifs
library(fields)       # Supplement image plots: legends, better colour schema
```

```{r prelims, echo = TRUE}
## --- Initial values -------- ##
M  <- 100                       # No. of simulations
N  <- 1000                      # No. of obs
NF <- 2^ceiling(log(N,2)) + 1   # No. of Fourier freqs
FF <- 1/(2*NF)                  # Fundamental Fourier freq
Fs <- FF*(0:(NF-1))             # Fourier freq mesh
t  <- 1:N                       # Time vector
w  <- 0.004                     # Analysis bandwidth (freq)
i  <- complex(1,0,1)            # imaginary i
K  <- 7                         # Eigencoefs per frequency
v  <- spec.mtm(ts(1:N), plot = FALSE)$mtm$dpss$v # DPSS (based on series length)

## --- Variables dependent on B (defined here for later use in plotting)
B  <- 200                       # Block size (for sliding window)
B2 <- ceiling(B/2)              # Midpoint shift
b  <- 1:(N-(B-1))               # block indices
tb <- b + B2 - 1                # time in-block
vb <- spec.mtm(ts(1:B), plot = FALSE)$mtm$dpss$v # DPSS (based on block size)


## --- Modulating function
ct1  <- exp((-(t-450)^2)/(2*(200^2))) # default
ct2  <- sqrt(1 + t/200)               # alternate
ct3  <- 1 - ct1                       # reversed
ct <- ct1 ; cc <- "c1"                # --- choose!
gt <- ct^2                            # squared (estimated later via S_X)

## --- Function: true spectral density of an AR(2) series (sd = 10 is fixed)
ar2 <- function(phi = c(0,0)){ (10^2)/Mod( 1 - phi[1]*exp(-i*2*pi*Fs) - phi[2]*(exp(-i*4*pi*Fs)))^2 }
```


# p-BC Function

```{r bcmtfse_cbcmtfse_sims}
## --------------- p-BC FUNCTION --------------- ##
p.bc <- function(p = 2, type = "noise", B = 100, M = 100, seed = 0,
               ct = rep(1,N), ct2 = rep(1,N), 
              ar2 = c(0.5,-0.5), ar2.2 = c(0.7,-0.3),
             freq = NULL){ 
  
        # Prelims
        B2 <- ceiling(B/2)                               # Midpoint shift
        vb <- spec.mtm(ts(1:B), plot = FALSE)$mtm$dpss$v # DPSS (based on block size)
        b  <- 1:(N-(B-1))                                # block indices
        tb <- b + B2 - 1                                 # time in-block
        
        
  # N x inner sum coef                    /----w_B----\
  Ma  <- function(t,m){return(B*(sin(2*pi *(K+1)/(2*B)* (t-m))/(pi*(t-m)))^2)}
        
  # Matrix of Interest
  mat <- matrix(0,nrow = B, ncol = B)
  for(s in 1:B){mat[s,] <- Ma(s,1:B)}
        
  # Fill diagonal with Sinc function at "0/0"
  diag(mat) <- 1 
      
  # Get eigenstuff
  mval <- eigen(mat)$values
  mvec <- eigen(mat)$vectors

  
        # Function to estimate coefficients {a(l,b)}
        a  <- function(s,l,b){ (K/(B*(mval[l+1]))) * (mvec[,l+1] %*% matrix(s[,b], ncol = NF)) }
              
        # omega function vals for upcoming Taylor expansions (compute prior to loop for speed)
        w0.0 <- sum(mvec[,1])
        w2.0 <- sum(mvec[,3])
        w1.1 <- c(((-B2):(B2 - 1 - (B/2 != B2)))   %*% mvec[,2])
        w0.2 <- c(((-B2):(B2 - 1 - (B/2 != B2)))^2 %*% mvec[,1])
        w2.2 <- c(((-B2):(B2 - 1 - (B/2 != B2)))^2 %*% mvec[,3])
        d.02 <- (w2.0*w0.2 - w0.0*w2.2)

        # Functions for first and second time-derivatives
        tdtfse  <- function(s,p){ B*a(s,1,p)/w1.1 }
        stdtfse <- function(s,p){ 2*B * (a(s,0,p)*w2.0 - a(s,2,p)*w0.0) / d.02}
  
        
  # Loop setup
  if(seed > 0){ set.seed(seed) }
  pb <- txtProgressBar(style = 3)
  
  # Initialize arrays
  bc1.sims <- if(any(p==1)) {array(dim = c(N,NF,M))} else { NULL }
  bc2.sims <- if(any(p==2)) {array(dim = c(N,NF,M))} else { NULL }
  
  
        # Get signals --------- This is for storing to plot stuff later, might not need since we have freqs idk
        if(!is.null(freq)){
          st  <- list()
          ind <- 1
          for(f in freq){ st[[ind]] = cos(2*pi*Fs[f]*t); ind <- ind + 1 }
          sig <- rowSums(matrix(unlist(st), nrow = N))
          } else {st <- NULL; sig <- 0}
  
  # Get series based on type
    if(type == "noise"){
      get <- function(){ return(rnorm(N, sd = 10) + sig) }
    } else if(type == "AR2"){
      get <- function(){ return(arima.sim(model = list(ar = ar2, sd = 10), n = N)) }
    } else if(type == "UMP"){
      get <- function(){
          yt <- arima.sim(model = list(ar = ar2, sd = 10), n = N)  
          return(ct*yt)
      }
    } else if(type == "GUMP"){
      get <- function(){
          yt1 <- arima.sim(model = list(ar = ar2  , sd = 10), n = N)
          yt2 <- arima.sim(model = list(ar = ar2.2, sd = 10), n = N)
          return(ct*yt1 + ct2*yt2)
      }
    } else {error}
  
  ## --------- SIMULATE: loop begins HERE ------------ ##
  for(m in 1:M){

    xt <- get()
    
    # Sliding window: full window included
    sw <- (B/K) * Mod( sapply(b, function(p){
          vb %*% t(spec.mtm(ts(xt[(p):(p+B-1)]),
                            nFFT = (2*NF-1),
                            plot = FALSE,
                            returnInternals = TRUE)$mtm$eigenCoefs)}))^2
    
        # Endpoints: 1st derivative
        tdtfse.start <- tdtfse(sw,1)      
        tdtfse.end   <- tdtfse(sw,max(b)) 
        
        # Endpoints: 2nd derivative
        stdtfse.start <- stdtfse(sw,1)      
        stdtfse.end   <- stdtfse(sw,max(b))
        
        # Heavy lifting done 
        gc(); setTxtProgressBar(pb, (m-0.5)/M)
    
    
    # --------- 1-BC (Boundary Corrected SWHRS using Taylor polynomials of degree 1)
    # Formerly: BCMTFSE (Boundary Corrected Modified Time Frequency Spectrum Estimate)
    if(any(p==1)){
      # Modify (linear) storing midpoints
      bc1.sims[tb,,m] <- (K/mval[1]) * t(sapply(b, function(p){mvec[,1] %*% matrix(sw[,p], ncol = NF)})) / w0.0  
      # Extrapolate
      bc1.sims[1:(tb[1]-1),,m]   <- t(sapply((tb[1]-1):1, function(h){ bc1.sims[tb[1],,m] - h*tdtfse.start }))
      bc1.sims[(max(tb)+1):N,,m] <- t(sapply(1:(B2-(B2 != B/2)), function(h){ bc1.sims[max(tb),,m] + h*tdtfse.end }))
    }
    
    
    # --------- 2-BC (Boundary Corrected SWHRS using Taylor polynomials of degree 2)
    # Formerly CBCMTFSE (Curvy Boundary Corrected Modified Time Frequency Spectrum Estimate)
    if(any(p==2)){
      # Modify (quadratic) storing midpoints
      bc2.sims[tb,,m] <- t(sapply(b, function(p){ B*(a(sw,2,p)*w0.2 - a(sw,0,p)*w2.2) / d.02 }))
      # Extrapolate
      bc2.sims[1:(tb[1]-1),,m]   <- t(sapply((tb[1]-1):1, function(h){ 
          bc2.sims[tb[1],,m] - h*tdtfse.start - (h^2)*stdtfse.start/2 }))
      bc2.sims[(max(tb)+1):N,,m] <- t(sapply(1:(B2-(B2 != B/2)), function(h){ 
          bc2.sims[max(tb),,m] + h*tdtfse.end + (h^2)*stdtfse.end/2 }))
    }
    
    # Clean!
    rm(sw); gc()
  
    # Phew!
    setTxtProgressBar(pb, m/M); gc()
  } # -------------------------- loop ends -------------------------- #
  
  # TRUE values
  zf.true  <- rep(10^2,NF)
  ztf.true <- outer(rep(1,N), zf.true)
  
  yf.true  <- if(type != "noise"){ar2(ar2)  } else {NULL}
  ytf.true <- if(type != "noise"){outer(rep(1,N), yf.true )} else {NULL}
  
  yf2.true  <- if(type == "GUMP"){ar2(ar2.2)} else {NULL}
  ytf2.true <- if(type == "GUMP"){outer(rep(1,N), yf2.true)} else {NULL}
  
  xtf.true  <- if((type == "UMP") || (type == "GUMP")){outer(ct^2, yf.true)} else {NULL}
  xtf2.true <- if(type == "GUMP"){outer(ct2^2, yf2.true)} else {NULL}
  
  # Save true vals
  tru <- list(zf.true, ztf.true, yf.true, ytf.true, yf2.true, ytf2.true, xtf.true, xtf2.true, st)
  names(tru) <- c("zf", "ztf", "yf", "ytf", "yf2", "ytf2", "xtf", "xtf2", "signals")
  
  # output
  return(list(bc1 = bc1.sims,
              bc2 = bc2.sims,
              tru = tru))
}
```

---

# Simulate

```{r}
my.type <- "UMP"
trial <- p.bc(p = 1:2, type = my.type, M = M, B = B, seed = 68, ct = ct); gc()
```

```{r}
## --- Stats --------- ##
pbc <- list(bc1 = list(), bc2 = list())
tru <- trial$tru; 

pbc$bc1$mean <- pbapply(trial$bc1, 1:2, mean); gc()
pbc$bc1$se   <- pbapply(trial$bc1, 1:2, sd)/sqrt(M); gc()

pbc$bc2$mean <- pbapply(trial$bc2, 1:2, mean); gc()
pbc$bc2$se   <- pbapply(trial$bc2, 1:2, sd)/sqrt(M); gc()
```


```{r save0}
## --- Save! --------- ##
save.image(paste0("Data/","B",B,"_",cc,"_",my.type,"_full.RData"))

rm(trial); gc() # discard individual simulations, keep stats

save.image(paste0("Data/","B",B,"_",cc,"_",my.type,"_mini.RData"))
```

