### Setup

```{r}
## --- Packages ------------------------------------ ##
library(multitaper)
library(pbapply)
library(kableExtra)
library(itsmr)
library(animation)
library(fields, quietly = TRUE, warn.conflicts = FALSE)

## --- Splot + Spalette ---------------------------- ##
load("C:/Users/skyep/Documents/Research/Plot_Animations/splot.RData")
```




# Spectrograms

## Noise \& AR(2)

```{r setupSgram_zy}
## --- Load 
load(file = "Data/noise_B200_mini.RData")
bc.z  <- bc
cbc.z <- cbc
tru.z <- tru

load(file = "Data/AR2_B200_mini.RData")
bc.y  <- bc
cbc.y <- cbc
tru.y <- tru

## --- Scaling & plot limits
# check
range(bc.z$mean);range(cbc.z$mean);range(tru.z$zf)
range(bc.y$mean);range(cbc.y$mean);range(tru.y$yf)

bc.y$mean  <- bc.y$mean *1e2  # scale
cbc.y$mean <- cbc.y$mean*1e2

zlim.z <- range(tru.z$zf, bc.z$mean, cbc.z$mean)
zlim.y <- range(tru.y$yf, bc.y$mean, cbc.y$mean)
```

```{r Sgram_xy}

png(filename = paste0("NewPlots/sgrams_Noise-AR2_B",B,"_letterbox.png"),
    width = 8.5, height = 11, units = "in", res = 200, bg = skrown$salt, pointsize = 8)
## ----------------------------------------------------------------------------------

      ## --- MARGINS
      par(mfrow = c(3,2), oma = c(4,1,4,3), mar = c(9,5,0,2))


  ## --- TRUE Z 
  image(x = Fs, y = t, z = t(tru.z$ztf),
        xlab = "", ylab = "", zlim = zlim.z,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$B2, lty = 2)
  slab("True Time-Frequency Spectrum: White Noise z(t)","",
       "Frequency","Time")
  
  ## --- TRUE Y
  image(x = Fs, y = t, z = t(tru.y$ytf),
        xlab = "", ylab = "", zlim = zlim.y,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("True Time-Frequency Spectrum: AR(2) series y(t)","",
       "Frequency","Time")


  ## --- BC Z
  image(x = Fs, y = t, z = t(bc.z$mean),
        xlab = "", ylab = "", zlim = zlim.z,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$B2, lty = 2)
  slab("BCMTFSE:  White Noise x(t)","",
       "Frequency","Time")
  
  ## --- BC Y
  image(x = Fs, y = t, z = t(bc.y$mean),
        xlab = "", ylab = "", zlim = zlim.y,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("BCMTFSE:  AR(2) series y(t)","",
       "Frequency","Time")


  ## --- CBC Z
  image(x = Fs, y = t, z = t(cbc.z$mean),
        xlab = "", ylab = "", zlim = zlim.z,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$B2, lty = 2)
  slab("CBCMTFSE:  White Noise x(t)","",
       "Frequency","Time")
  image.plot(legend.only = TRUE , legend.lab = "Power",
             legend.line = -3.5, legend.cex = 0.9,
             zlim = zlim.z,
             horizontal = TRUE, smallplot = c(0.11,0.96,0,0.05))
  
  ## --- CBC Y
  image(x = Fs, y = t, z = t(cbc.y$mean),
        xlab = "", ylab = "", zlim = zlim.y,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("CBCMTFSE:  AR(2) series y(t)","",
       "Frequency","Time")
  image.plot(legend.only = TRUE , legend.lab = "Power",
             legend.line = -3.5, legend.cex = 0.9,
             zlim = zlim.y,
             horizontal = TRUE, smallplot = c(0.11,0.96,0,0.05))

## ----------------------------------------------------------------------------------
dev.off()

```

## UMP

```{r setupSgram_z}
## --- Load 
load(file = "Data/UMP_B200_mini_rev.RData")
bc.x  <- bc
cbc.x <- cbc
tru.x <- tru

## --- Scaling & plot limits
# check
range(bc.x$mean);range(cbc.x$mean);range(tru.x$xtf)

bc.x$mean  <- bc.x$mean *1e2  # scale
cbc.x$mean <- cbc.x$mean*1e2

zlim.x <- range(tru.x$xtf, bc.x$mean, cbc.x$mean)
```

```{r Sgram_z}

png(filename = paste0("NewPlots/sgrams_UMP_B",B,"_rev_letterbox.png"),
    width = 12.6, height = 4.2, units = "in", res = 200, bg = skrown$salt, pointsize = 8)
## ----------------------------------------------------------------------------------

  # Margins
  par(mfrow = c(1,3), oma = c(0,3,0,5))
  
  # --- TRUE
  image(x = Fs, y = t, z = t(tru.x$xtf),
        xlab = "", ylab = "", zlim = zlim.x,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("True TFS: UMP x(t)",
       "","Frequency","Time"); gc()
  
  # --- BC
  image(x = Fs, y = t, z = t(bc.x$mean),
        xlab = "", ylab = "", zlim = zlim.x,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("BCMTFSE:  UMP x(t)",
       "","Frequency","Time"); gc()
  
  # --- CBC
  image(x = Fs, y = t, z = t(cbc.x$mean),
        xlab = "", ylab = "", zlim = zlim.x,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("CBCMTFSE:  UMP x(t)",
       "","Frequency","Time"); gc()
  
  # --- Legend
  par(oma = c(0,0,0,3))
  image.plot(legend.only = TRUE,
             zlim = zlim.x, legend.shrink = 1, legend.width = 2)

## ----------------------------------------------------------------------------------
dev.off()

```

## GUMP

```{r setupSgram_z}
## --- Load 
load("Data/GUMP_B100_mini.RData")
bc.x  <- bc
cbc.x <- cbc
tru.x <- tru

## --- Scaling & plot limits
# check
range(bc.x$mean);range(cbc.x$mean);range(tru.x$xtf2)

bc.x$mean  <- bc.x$mean *1e2  # scale
cbc.x$mean <- cbc.x$mean*1e2

zlim.x <- range(tru.x$xtf2, bc.x$mean, cbc.x$mean)
```

```{r Sgram_z}

png(filename = paste0("NewPlots/sgrams_",my.type,"_B",B,".png"),
    width = 12.6, height = 4.2, units = "in", res = 200, bg = skrown$salt, pointsize = 8)
## ----------------------------------------------------------------------------------

  # Margins
  par(mfrow = c(1,3), oma = c(0,3,0,5))
  
  # --- TRUE
  image(x = Fs, y = t, z = t(tru.x$xtf2),
        xlab = "", ylab = "", zlim = zlim.x,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("True TFS: GUMP x(t)",
       "","Frequency","Time"); gc()
  
  # --- BC
  image(x = Fs, y = t, z = t(bc.x$mean),
        xlab = "", ylab = "", zlim = zlim.x,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("BCMTFSE:  GUMP x(t)",
       "","Frequency","Time"); gc()
  
  # --- CBC
  image(x = Fs, y = t, z = t(cbc.x$mean),
        xlab = "", ylab = "", zlim = zlim.x,
        las = 1, col = tim.colors()); sox()
  abline(h = range(tb), col = skrown$salt, lty = 2)
  slab("CBCMTFSE:  GUMP x(t)",
       "","Frequency","Time"); gc()
  
  # --- Legend
  par(oma = c(0,0,0,3))
  image.plot(legend.only = TRUE,
             zlim = zlim.x, legend.shrink = 1, legend.width = 2)

## ----------------------------------------------------------------------------------
dev.off()

```

# C estimators

```{r}
# what g(t) are you usng?
vers <- 1 + (gt[1] > gt[10])
rev <- if(vers > 1){"_rev"} else {""}
```

## Plotting g(t) obtained from Mean Spectrograms (CHEAT)

```{r plot_compare, echo = FALSE, fig.dim = c(12,8)}
png(filename = paste0("NewPlots/gest_UMP_B",B,"_B",B,"_rev.png"),
# png(filename = paste0("NewPlots/gest_UMP_B",B,".png"),
    width = 12.6, height = 9, units = "in", res = 200, bg = skrown$salt, pointsize = 10)
# ----------------------------------------------------------------------------------------
par(mfrow = c(2,2), mar = c(4,4,4.4,1))
lim <- range(ct, g.bc, g.cbc)
# --- BC
splot(t, ct^2 , type = "l", ylim = lim, colr = skrown$smoke, labs = FALSE, lwd = 2)
lines(   g.bc , col = skaturate$blue, lwd = 2)
slab(main = "Estimation of g(t) based on BC",
     subb = bquote(hat(g)*" is the solution to:    (1/N)Ag = g"),
     xlab = "Time", ylab = "g(t)")
legend("top", legend = c("True g(t)", "BC", paste("B =",B)),
       col = c("black", skaturate$blue),
       lwd = c(2,2,NA), inset = 0.01)

# --- CBC
splot(t, ct^2 , type = "l", ylim = lim, colr = skrown$smoke, labs = FALSE, lwd = 2)
lines(   g.cbc, col = skol$orange, lwd = 2)
slab(main = "Estimation of g(t) based on CBC",
     subb = bquote(hat(g)*" is the solution to:    (1/N)Ag = g"),
     xlab = "Time", ylab = "g(t)")
legend("top", legend = c("True g(t)", "CBC", paste("B =",B)),
       col = c("black", skol$orange),
       lwd = c(2,2,NA), inset = 0.01)
# ----------------------------------------------------------------------------------------
dev.off()

```

### Plotting g(t) obtained from individual sims

```{r}
# load("Data/gest_UMP_B200_mini.RData")
# load("Data/gest_UMP_B200_rev_mini.RData")
# load("Data/gest_UMP_B400_mini.RData")
# load("Data/gest_UMP_B400_rev_mini.RData")
```

#### Single Comparison

```{r}

png(filename = paste0("NewPlots/gest_",my.type,"_B",B,rev,".png"),
width = 12, height = 5, units = "in", res = 200, bg = skrown$salt, pointsize = 10)
# ----------------------------------------------------------------------------------------
    par(mfrow = c(1,2), mar = c(4,4,4.4,1))
    lim <- range(gt, g.bc, g.cbc)
    
    # --- BC
    splot(t, gt , type = "l", ylim = lim, labs = 0, lwd = 2)
    lines(g.bc$mean, col = skaturate$blue, lwd = 2)
    lines(g.bc$UCL , col = skastel$blue)
    lines(g.bc$LCL , col = skastel$blue)
    abline(v = range(tb), col = skrown$B1, lty = 2)
    slab(main = bquote("Estimation of"~hat(g)[.(vers)]~"(t) based on BC"),
         subb = bquote("Blockwidth B ="~.(B)),
         xlab = "Time", ylab = "g(t)")
    legend(if(vers>1){"top"}else{"topright"},
           legend = c("True g(t)", bquote(hat(g)~"mean ("*mu*") "), bquote(hat(g)~mu~"+/- 2se  ")),
           col = c(skrown$B2, skaturate$blue, skastel$blue),
           lwd = c(2,2,1), inset = 0.01, y.intersp = 1.25, cex = 0.9)
    
    # --- CBC
    splot(t, gt , type = "l", ylim = lim, labs = 0, lwd = 2)
    lines(g.cbc$mean, col = skol$orange, lwd = 2)
    lines(g.cbc$UCL , col = skaturate$yellow)
    lines(g.cbc$LCL , col = skaturate$yellow)
    abline(v = range(tb), col = skrown$B1, lty = 2)
    slab(main = bquote("Estimation of"~hat(g)[.(vers)]~"(t) based on CBC"),
         subb = bquote("Blockwidth B ="~.(B)),
         xlab = "Time", ylab = "g(t)")
    legend(if(vers>1){"top"}else{"topright"},
           legend = c("True g(t)", bquote(hat(g)~"mean ("*mu*") "), bquote(hat(g)~mu~"+/- 2se  ")),
           col = c(skrown$B2, skol$orange, skaturate$yellow),
           lwd = c(2,2,1), inset = 0.01, y.intersp = 1.25, cex = 0.9)
    
# ----------------------------------------------------------------------------------------
dev.off()
    
```

#### Multi-Comparison

```{r}

png(filename = paste0("NewPlots/gest_UMP_B200_B400.png"),
    width = 12, height = 16, units = "in", res = 200, bg = skrown$salt, pointsize = 12)
# png(filename = paste0("NewPlots/gest_UMP_B",B,".png"),
# width = 12, height = 16, units = "in", res = 200, bg = skrown$salt, pointsize = 10)

# ----------------------------------------------------------------------------------------
par(mfrow = c(3,2))
# par(mfrow = c(1,2))


# --------- B = 200 --------- #
load("Data/gest_UMP_B200_mini.RData")
lim <- range(gt, g.bc, g.cbc)

# --- BC
splot(t, gt , type = "l", ylim = lim, labs = 0, lwd = 2)
lines(g.bc$mean, col = skaturate$blue, lwd = 2)
lines(g.bc$UCL , col = skastel$blue)
lines(g.bc$LCL , col = skastel$blue)
abline(v = range(tb), col = skrown$B1, lty = 2)
slab(main = bquote("Estimation of"~hat(g)[.(vers)]~"(t) based on BC"),
     subb = bquote("Blockwidth B ="~.(B)),
     xlab = "Time", ylab = "g(t)")
legend(if(vers>1){"top"}else{"topright"},
       legend = c("True g(t)", bquote(hat(g)~"mean ("*mu*") "), bquote(hat(g)~mu~"+/- 2se  ")),
       col = c(skrown$B2, skaturate$blue, skastel$blue),
       lwd = c(2,2,1), inset = 0.02, y.intersp = 1.25, cex = 1.1)

# --- CBC
splot(t, gt , type = "l", ylim = lim, labs = 0, lwd = 2)
lines(g.cbc$mean, col = skol$orange, lwd = 2)
lines(g.cbc$UCL , col = skaturate$yellow)
lines(g.cbc$LCL , col = skaturate$yellow)
abline(v = range(tb), col = skrown$B1, lty = 2)
slab(main = bquote("Estimation of"~hat(g)[.(vers)]~"(t) based on CBC"),
     subb = bquote("Blockwidth B ="~.(B)),
     xlab = "Time", ylab = "g(t)")
legend(if(vers>1){"top"}else{"topright"},
       legend = c("True g(t)", bquote(hat(g)~"mean ("*mu*") "), bquote(hat(g)~mu~"+/- 2se  ")),
       col = c(skrown$B2, skol$orange, skaturate$yellow),
       lwd = c(2,2,1), inset = 0.02, y.intersp = 1.25, cex = 1.1)




# --------- B = 200 REV --------- # 
load("Data/gest_UMP_B200_rev_mini.RData")
lim <- range(gt, g.bc, g.cbc)

# --- BC
splot(t, gt , type = "l", ylim = lim, labs = 0, lwd = 2)
lines(g.bc$mean, col = skaturate$blue, lwd = 2)
lines(g.bc$UCL , col = skastel$blue)
lines(g.bc$LCL , col = skastel$blue)
abline(v = range(tb), col = skrown$B1, lty = 2)
slab(main = bquote("Estimation of"~hat(g)[2]~"(t) based on BC"),
     subb = bquote("Blockwidth B ="~.(B)),
     xlab = "Time", ylab = "g(t)")
legend(if(vers>1){"top"}else{"topright"},
       legend = c("True g(t)", bquote(hat(g)~"mean ("*mu*") "), bquote(hat(g)~mu~"+/- 2se  ")),
       col = c(skrown$B2, skaturate$blue, skastel$blue),
       lwd = c(2,2,1), inset = 0.02, y.intersp = 1.25, cex = 1.1)

# --- CBC
splot(t, gt , type = "l", ylim = lim, labs = 0, lwd = 2)
lines(g.cbc$mean, col = skol$orange, lwd = 2)
lines(g.cbc$UCL , col = skaturate$yellow)
lines(g.cbc$LCL , col = skaturate$yellow)
abline(v = range(tb), col = skrown$B1, lty = 2)
slab(main = bquote("Estimation of"~hat(g)[2]~"(t) based on CBC"),
     subb = bquote("Blockwidth B ="~.(B)),
     xlab = "Time", ylab = "g(t)")
legend(if(vers>1){"top"}else{"topright"},
       legend = c("True g(t)", bquote(hat(g)~"mean ("*mu*") "), bquote(hat(g)~mu~"+/- 2se  ")),
       col = c(skrown$B2, skol$orange, skaturate$yellow),
       lwd = c(2,2,1), inset = 0.02, y.intersp = 1.25, cex = 1.1)




# --------- B = 400 REV --------- #
load("Data/gest_UMP_B400_rev_mini.RData")
lim <- range(gt, g.bc, g.cbc)

# --- BC
splot(t, gt , type = "l", ylim = lim, labs = 0, lwd = 2)
lines(g.bc$mean, col = skaturate$blue, lwd = 2)
lines(g.bc$UCL , col = skastel$blue)
lines(g.bc$LCL , col = skastel$blue)
abline(v = range(tb), col = skrown$B1, lty = 2)
slab(main = bquote("Estimation of"~hat(g)[.(vers)]~"(t) based on BC"),
     subb = "Blockwidth B=400",
     xlab = "Time", ylab = "g(t)")
legend(if(vers>1){"top"}else{"topright"},
       legend = c("True g(t)", bquote(hat(g)~"mean ("*mu*") "), bquote(hat(g)~mu~"+/- 2se  ")),
       col = c(skrown$B2, skaturate$blue, skastel$blue),
       lwd = c(2,2,1), inset = 0.02, y.intersp = 1.25, cex = 1.1)

# --- CBC
splot(t, gt , type = "l", ylim = lim, labs = 0, lwd = 2)
lines(g.cbc$mean, col = skol$orange, lwd = 2)
lines(g.cbc$UCL , col = skaturate$yellow)
lines(g.cbc$LCL , col = skaturate$yellow)
abline(v = range(tb), col = skrown$B1, lty = 2)
slab(main = bquote("Estimation of"~hat(g)[.(vers)]~"(t) based on CBC"),
     subb = "Blockwidth B=400",
     xlab = "Time", ylab = "g(t)")
legend(if(vers>1){"top"}else{"topright"},
       legend = c("True g(t)", bquote(hat(g)~"mean ("*mu*") "), bquote(hat(g)~mu~"+/- 2se  ")),
       col = c(skrown$B2, skol$orange, skaturate$yellow),
       lwd = c(2,2,1), inset = 0.02, y.intersp = 1.25, cex = 1.1)
# ----------------------------------------------------------------------------------------
dev.off()
```


# Smoothed Spectrograms

## Not cheating

```{r}
# load("Data/gest_UMP_B200_mini.RData")
# load("Data/gest_UMP_B200_rev_mini.RData")
load("Data/gest_UMP_B400_rev_mini.RData")
```

```{r}
png(filename = paste0("NewPlots/smoothgrams_UMP_B",B,rev,"_letterbox.png"),
    width = 12.6, height = 4.2, units = "in", res = 200, bg = skrown$salt, pointsize = 8)
## ----------------------------------------------------------------------------------

par(mfrow = c(1,3), mar = c(9,4.4,4.4,1), oma = c(2.5,0,0,0))
# mat <- matrix(rep(1,16), ncol = 4)
# image(mat)

# TRUE
image(Fs, t, t(tru$xtf), zlim = range(tru$xtf),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
slab("True TFS: UMP", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(tru$xtf),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

image(Fs, t, bc.smooth , zlim = range( bc.smooth),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
abline(h = range(tb), col = skrown$salt, lty = 2)
slab("Smoothed BC", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(bc.smooth),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

image(Fs, t, cbc.smooth , zlim = range( cbc.smooth),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
abline(h = range(tb), col = skrown$salt, lty = 2)
slab("Smoothed CBC", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(cbc.smooth),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

## ----------------------------------------------------------------------------------
dev.off()
```


## Really not cheating

```{r}
# load("Data/gest_UMP_B200_full.RData")
# load("Data/gest_UMP_B200_rev_full.RData")
# load("Data/gest_UMP_B400_rev_full.RData")

# what g(t) are you usng?
vers <- 1 + (gt[1] > gt[10])
rev <- if(vers > 1){"_rev"} else {""}
```

```{r}
png(filename = paste0("NewPlots/smoothgrams_UMP_B",B,rev,"_single.png"),
    width = 12.6, height = 4.2, units = "in", res = 200, bg = skrown$salt, pointsize = 8)
## ----------------------------------------------------------------------------------

par(mfrow = c(1,3), mar = c(9,4.4,4.4,1), oma = c(2.5,0,0,0))
# mat <- matrix(rep(1,16), ncol = 4)
# image(mat)

# TRUE
image(Fs, t, t(tru$xtf), zlim = range(tru$xtf),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
slab("True TFS: UMP", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(tru$xtf),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

image(Fs, t, bc.smooth , zlim = range( bc.smooth),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
abline(h = range(tb), col = skrown$salt, lty = 2)
slab("Smoothed BC", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(bc.smooth),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

image(Fs, t, cbc.smooth , zlim = range( cbc.smooth),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
abline(h = range(tb), col = skrown$salt, lty = 2)
slab("Smoothed CBC", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(cbc.smooth),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

## ----------------------------------------------------------------------------------
dev.off()
```


## Single instance: no smooth

```{r}
png(filename = paste0("NewPlots/smoothgrams_UMP_B",B,rev,"_raw.png"),
    width = 12.6, height = 4.2, units = "in", res = 200, bg = skrown$salt, pointsize = 8)
## ----------------------------------------------------------------------------------

par(mfrow = c(1,3), mar = c(9,4.4,4.4,1), oma = c(2.5,0,0,0))
# mat <- matrix(rep(1,16), ncol = 4)
# image(mat)

# TRUE
image(Fs, t, t(tru$xtf), zlim = range(tru$xtf),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
slab("True TFS: UMP", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(tru$xtf),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

image(Fs, t, t(bc.samp) , zlim = range( bc.samp),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
abline(h = range(tb), col = skrown$salt, lty = 2)
slab("Smoothed BC", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(bc.smooth),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

image(Fs, t, t(cbc.samp) , zlim = range( cbc.samp),
      xlab = "", ylab = "", las = 1, col = tim.colors()); sox(); gc()
abline(h = range(tb), col = skrown$salt, lty = 2)
slab("Smoothed CBC", bquote("Modulating function g"[.(vers)]*"(t)"), "Frequency", "Time")
image.plot(legend.only = TRUE, legend.lab = "Power", zlim = range(cbc.smooth),
           legend.line = -4, legend.cex = 0.9,
           horizontal  = TRUE, smallplot  = c(0.11,0.96,0,0.05))

## ----------------------------------------------------------------------------------
dev.off()
```


# Spectrogram ColMeans for Stationary Series

```{r}
png(filename = paste0("NewPlots/smooth_yf_",my.type,"_B",B,".png"),
width = 12, height = 5, units = "in", res = 200, bg = skrown$salt, pointsize = 10)
# ----------------------------------------------------------------------------------------

    par(mfrow = c(1,2), mar = c(4,4,4.4,1))
    
    ## -------- M = 100 --------- ##
    
    # --- load
    load("Data/AR2_B200_mini.RData")
    
    # --- Prep
    lim <- range(yf.mtm, yf.bc, yf.cbc, tru$yf/1e2)
    
    # --- Plot
    splot(Fs, tru$yf/1e2, ylim = lim, type = "l", lwd = 2, labs = 0)
    lines(Fs, yf.mtm, col = skastel$green)
    sadd (Fs, list(yf.bc, yf.cbc), type = "l", lwd = 2, col = list(skaturate$blue, skaturate$yellow))
    slab("Spectrum Estimates for Stationary AR(2) Series",
         "Smooth Estimates taken from Mean Spectrogram over M=100 Simulations",
         "Frequency", bquote("Spectrum: "~S[Y]*"(f)"), yline = 2.5)
    legend("topright", legend = c("Theoretical", "Smooth BC", "Smooth CBC", "MTM"),
           lty = 1, lwd = 2, inset = 0.05,
           col = c(skrown$B2, skaturate$blue, skaturate$yellow, skastel$green))
    
    ## --------- M = 1 --------- ##
    
    # --- load
    load("Data/AR2_B200_samp.RData")
    
    # --- Prep
    lim <- range(yf.mtm, yf.bc, yf.cbc, tru$yf/1e2)
    
    # --- Plot
    splot(Fs, tru$yf/1e2, ylim = lim, type = "l", lwd = 2, labs = 0)
    lines(Fs, yf.mtm, col = skastel$green)
    sadd (Fs, list(yf.bc, yf.cbc), type = "l", lwd = 2, col = list(skaturate$blue, skaturate$yellow))
    slab("Spectrum Estimates for Stationary AR(2) Series",
         "All Estimates taken from a Single Simulation (M=1)",
         "Frequency", bquote("Spectrum: "~S[Y]*"(f)"), yline = 2.5)
    legend("topright", legend = c("Theoretical", "Smooth BC", "Smooth CBC", "MTM"), lty = 1, lwd = 2, inset = 0.05,
           col = c(skrown$B2, skaturate$blue, skaturate$yellow, skastel$green))
# ----------------------------------------------------------------------------------------
dev.off()
```









# Animations

## Frequency-Domain Animations

```{r}
## --- Choose your series
load("C:/Users/skyep/Documents/Research/PhD_Proposal/Data/")
```

```{r ani_prep}
## --- Plot Prep ---------------- ###

# Confidence Intervals (if it were Gaussian... isn't it more chi^2?)
bc.low   <-  bc$mean - 2* bc$se
bc.high  <-  bc$mean + 2* bc$se
cbc.low  <- cbc$mean - 2*cbc$se
cbc.high <- cbc$mean + 2*cbc$se

# ylims
ylim <- range(bc.low, cbc.low, bc.high, cbc.high)

# Spectrogram limit
zlim <- range(xtf.true/1e4, bc$mean, cbc$mean)
```

```{r f_domain_gif}

p <- 0
pb <- txtProgressBar(style = 3)

### --- Create GIF ------------------- ###

saveGIF({  for (my.t in seq(1,N,by = 5)) {
  
  # --- True Plot
  splot(Fs, ztf.true[my.t,]/1e4, type = "l", ylim = ylim.tx, lwd = 2, colr = "#FCF8F8"); gc()
  
  # --- Means
  lines(Fs,  bc$mean[my.t,], col = "dodgerblue2", lwd = 2) # OLD bc
  lines(Fs, cbc$mean[my.t,], col = "goldenrod"  , lwd = 2) # Cbc  
  
  # --- Standard Errors
  lines(Fs, bc.low [my.t,] , col = skol$blue  , lwd = 1)                     
  lines(Fs, bc.high[my.t,] , col = skol$blue  , lwd = 1)                     
  
  lines(Fs, cbc.low [my.t,], col = skol$orange, lwd = 1)                     
  lines(Fs, cbc.high[my.t,], col = skol$orange, lwd = 1)                     
  
  # --- Labels
  slab(main = "Spectrogram Estimates: UMP: c(t)*AR(2)",
       subb = bquote("c(t) = exp{ (-t-500)"^2*"/(2(200"^2*")) }        Blockwidth B ="~.(B)),
       xlab = "Frequency",
       ylab = bquote(hat(S)[X]~"(t = "*.(my.t)*", f)")); gc()
  
  
  ## --- Legends (& other graphics) --------------------------- ##
  legend("topright",
         legend = c("means","mean +/- 2se","",
                    "True spectrum at t",
                    "BCMTFSE",
                    "CBCMTFSE"),
         lty = c( 1, 1,NA,    1,NA,NA),
         lwd = c( 3, 1,NA,   NA,NA,NA),
         pch = c(NA,NA,NA,   19,19,19),
         
         col = c(skol$brown4, skol$brown4, skol$brown4,     skol$brown4,"dodgerblue2","goldenrod"),
         bg  = "white",
         inset = c(0.01,0.02)
    )
  legend("topleft", legend = bquote("Time t ="*.(my.t)*"  "),
         inset = c(0.05,0.08), cex = 2.5,
         bg = if((my.t >= tb[1]) & (my.t <= max(tb))) {skol$green} else {"#F4A4A8"})
  ## ---------------------------------------------------------- ##  
  
  gc()
    p <- p+1
    setTxtProgressBar(pb, p/500)

    } },
  
  # --- GIF details
  interval   = 0.1,
  movie.name = paste0("~/Plots/",my.type,"_B",B,".gif"),
  ani.height = 668, ani.width = 1080); gc()
```























































